-- MySQL Script generated by MySQL Workbench
-- 07/17/14 12:58:35
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema servers
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `servers` ;
CREATE SCHEMA IF NOT EXISTS `servers` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `servers` ;

-- -----------------------------------------------------
-- Table `servers`.`machines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `servers`.`machines` ;

CREATE TABLE IF NOT EXISTS `servers`.`machines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servers`.`links`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `servers`.`links` ;

CREATE TABLE IF NOT EXISTS `servers`.`links` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source` INT NOT NULL,
  `destination` INT NOT NULL,
  `reason` VARCHAR(45) NOT NULL,
  INDEX `fk_links_machines_idx` (`source` ASC),
  INDEX `fk_links_machines1_idx` (`destination` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_links_machines`
    FOREIGN KEY (`source`)
    REFERENCES `servers`.`machines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_links_machines1`
    FOREIGN KEY (`destination`)
    REFERENCES `servers`.`machines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
